#!/usr/bin/env php
# autogenerated file; do not edit
language: c

addons:
 apt:
  packages:
   - php5-cli
   - php-pear
   - libcurl5-openssl-dev
   - zlib1g-dev
   - libidn11-dev
   - libevent-dev

env:
<?php

$gen = include "./travis/pecl/gen-matrix.php";
$env = $gen([
	"PHP" => ["5.4", "5.5", "5.6"],
	"enable_debug",
	"enable_maintainer_zts",
	"enable_json",
	"enable_hash" => ["yes"],
	"enable_iconv" => ["yes"]
]);
foreach ($env as $e) {
	printf(" - %s\n", $e);
}

?>

before_script:
 - make -f travis/pecl/Makefile php
 - make -f travis/pecl/Makefile pecl PECL=raphf
 - make -f travis/pecl/Makefile pecl PECL=propro

script:
 - make -f travis/pecl/Makefile ext PECL=http
 - make -f travis/pecl/Makefile test

sudo: false
