#!/usr/bin/env php
# autogenerated file; do not edit
language: c

addons:
 apt:
  packages:
   - php5-cli
   - php-pear
   - libcurl4-openssl-dev
   - zlib1g-dev
   - libidn11-dev
   - libevent-dev

env:
<?php

$gen = include "./travis/pecl/gen-matrix.php";
$env = $gen([
	"PHP" => ["master"],
	"enable_debug",
	"enable_maintainer_zts",
	"enable_json",
	"enable_hash" => ["yes"],
	"enable_iconv" => ["yes"]
]);
foreach ($env as $e) {
	printf(" - %s\n", $e);
}

?>

before_script:
 - make -f travis/pecl/Makefile php
 - make -f travis/pecl/Makefile raphf-phpng.ext.phar
 - make -f travis/pecl/Makefile propro-phpng.ext.phar

script:
 - make -f travis/pecl/Makefile ext PECL=http
 - make -f travis/pecl/Makefile test

after_script:
 - test -e tests/helper/server.log && cat tests/helper/server.log

sudo: false
