#!/bin/bash
rm -f warnings

if test -d "$1"; then
    PREFIX=$1
else
    PREFIX=/usr
fi

echo "Using prefix '$PREFIX' for phpize and php-config!"

echo -n "executing phpize... "
${PREFIX}/bin/phpize 2>&1 >/dev/null
if test $? -ne 0 ; then
    echo "FAILED!"
    exit 1
fi
echo "DONE"

echo -n "configuring... "
CFLAGS="-W -Wchar-subscripts -Wformat=2 -Wno-format-y2k -Wimplicit -Wmissing-braces -Wunused-variable  -Wbad-function-cast -Wpointer-arith -Wsign-compare -Winline" \
    ./configure --with-php-config=${PREFIX}/bin/php-config $2 >/dev/null
if test $? -ne 0 ; then
    echo "FAILED!"
    exit 1
fi
echo "DONE"

echo -n "building... "
make clean all 2>warnings >/dev/null
if test $? -ne 0 ; then
    echo "FAILED!"
else
    echo "DONE"
fi

if test -s warnings; then
    cat warnings
fi

