#!/bin/bash
rm -f warnings

if test -d "$1"; then
    PREFIX=$1
    shift
else
    PREFIX=`dirname $(dirname $(which php-config))`
fi

echo "Using prefix '$PREFIX' for phpize and php-config!"

echo -n "executing phpize... "
${PREFIX}/bin/phpize 2>&1 >/dev/null
if test $? -ne 0 ; then
    echo "FAILED!"
    exit 1
fi
echo "DONE"

echo -n "configuring... "
CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wfloat-equal -Wdeclaration-after-statement -Wundef -Wbad-function-cast -Wcast-align -Wmissing-field-initializers -Wnested-externs" \
    ./configure --with-php-config=${PREFIX}/bin/php-config $@ >/dev/null
if test $? -ne 0 ; then
    echo "FAILED!"
    exit 1
fi
echo "DONE"

echo -n "building... "
make clean all 2>warnings >/dev/null
if test $? -ne 0 ; then
    echo "FAILED!"
else
    echo "DONE"
fi

if test -s warnings; then
    grep -E "^/.+http" warnings
fi

